Object.assign(window, {
    docker_info: () => http_get_json('/api/v1/docker/info'),
    docker_version: () => http_get_json('/api/v1/docker/version'),
    docker_ping: () => http_get_json('/api/v1/docker/ping'),
    docker_events: () => http_get_json('/api/v1/docker/events'),
    docker_containers_list: () => http_get_json('/api/v1/docker/containers.json'),
    docker_containers_fetch: (id) => http_get_json(`/api/v1/docker/containers/${id}.json`),
    docker_containers_top: (id) => http_get_json(`/api/v1/docker/containers/${id}/top`),
    docker_containers_logs: (id) => http_get_json(`/api/v1/docker/containers/${id}/logs`),
    docker_containers_stats: (id) => http_get_json(`/api/v1/docker/containers/${id}/stats`),
    docker_containers_start: (id) => http_post_json(`/api/v1/docker/containers/${id}/start`),
    docker_containers_stop: (id) => http_post_json(`/api/v1/docker/containers/${id}/stop`),
    docker_containers_restart: (id) => http_post_json(`/api/v1/docker/containers/${id}/restart`),
    docker_containers_kill: (id) => http_post_json(`/api/v1/docker/containers/${id}/kill`),
    docker_containers_pause: (id) => http_post_json(`/api/v1/docker/containers/${id}/pause`),
    docker_containers_unpause: (id) => http_post_json(`/api/v1/docker/containers/${id}/unpause`),
    docker_containers_remove: (id) => http_delete(`/api/v1/docker/containers/${id}`),
});
