Object.assign(window, {
    docker_info: () => http_get_json('/api/v1/docker/info'),
    docker_version: () => http_get_json('/api/v1/docker/version'),
    docker_ping: () => http_get_json('/api/v1/docker/ping'),
    docker_events: () => http_get_json('/api/v1/docker/events'),
    docker_images_list: () => http_get_json('/api/v1/docker/images.json'),
    docker_images_fetch: (image_id) => http_get_json(`/api/v1/docker/images/${image_id}.json`),
    docker_images_history: (image_id) => http_get_json(`/api/v1/docker/images/${image_id}/history`),
    docker_containers_list: () => http_get_json('/api/v1/docker/containers.json'),
    docker_containers_fetch: (container_id) => http_get_json(`/api/v1/docker/containers/${container_id}.json`),
    docker_containers_top: (container_id) => http_get_json(`/api/v1/docker/containers/${container_id}/top`),
    docker_containers_logs: (container_id) => http_get_json(`/api/v1/docker/containers/${container_id}/logs`),
    docker_containers_stats: (container_id) => http_get_json(`/api/v1/docker/containers/${container_id}/stats`),
    docker_containers_start: (container_id) => http_post_json(`/api/v1/docker/containers/${container_id}/start`),
    docker_containers_stop: (container_id) => http_post_json(`/api/v1/docker/containers/${container_id}/stop`),
    docker_containers_restart: (container_id) => http_post_json(`/api/v1/docker/containers/${container_id}/restart`),
    docker_containers_kill: (container_id) => http_post_json(`/api/v1/docker/containers/${container_id}/kill`),
    docker_containers_pause: (container_id) => http_post_json(`/api/v1/docker/containers/${container_id}/pause`),
    docker_containers_unpause: (container_id) => http_post_json(`/api/v1/docker/containers/${container_id}/unpause`),
    docker_containers_remove: (container_id) => http_delete(`/api/v1/docker/containers/${container_id}`),
});
